import Navigation from '@/components/navigation'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='es'>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
